const actions = {
  GET_DATA: 'GET_DATA',
  GET_DATA_SUCCESS: 'GET_DATA_SUCCESS',
  GET_DATA_CURRENCY: 'GET_DATA_CURRENCY',
  GET_DATA_CURRENCY_SUCCESS: 'GET_DATA_CURRENCY_SUCCESS',
  GET_VAL_CURRENCY: 'GET_VAL_CURRENCY',
  GET_VAL_CURRENCY_SUCCESS: 'GET_VAL_CURRENCY_SUCCESS',
  SHOW_LOADER: 'SHOW_LOADER',
  HIDE_LOADER: 'HIDE_LOADER'
};
export default actions;

